- hosts: localhost
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: alpine
    default_container_command: sleep 1d
    golang_gopath: '$HOME/workspace-go'

  tasks:
  - name: Common tasks / tools
    import_tasks: common.yml

  - name: Install VPN, SSH remote access and keychain
    import_tasks: VPN-SSH.yml

  - name: Install Programming
    import_tasks: programming.yml

  - name: Install snaps
    import_tasks: snaps-flatpaks.yml

  - name: Install Applications
    import_tasks: applications.yml

  # - name: Install Docker
  #   import_tasks: docker.yml

  roles:
  - gantsign.visual-studio-code
  - gantsign.golang
  - pixelart.chrome
  - chaosmail.sublime-text
  # - geerlingguy.pip not yet 20.04
  # - geerlingguy.docker not yet 20.04


  # - { role: dotfiles }

  # - role: stephdewit.nvm
  #   nvm_version: HEAD

# TODO:

    # Install a snap with from a specific channel
  # - name: Install "Hugo" with option --channel=extended
  #   snap:
  #     name: hugo
  #     channel: extended

          #  - name: Install Hugo static site generator >> will install old version
          # apt: name=hugo
