- hosts: localhost
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: alpine
    default_container_command: sleep 1d
    golang_gopath: '$HOME/workspace-go'
    borg_encryption_passphrase: CHANGEME
    borg_repository: m5vz9gp4@m5vz9gp4.repo.borgbase.com:repo
    borg_source_directories:
      - /srv/www
      - /var/lib/automysqlbackup
    borg_exclude_patterns:
      - /srv/www/old-sites
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
    ubuntu_docker_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    docker_users:
    - joost

  tasks:
  - name: Common tasks / tools
    import_tasks: common.yml

  - name: Install VPN, SSH remote access and keychain
    import_tasks: VPN-SSH.yml

  - name: Install Programming
    import_tasks: programming.yml

  - name: Install snaps
    import_tasks: snaps-flatpaks.yml

  - name: Install Applications
    import_tasks: applications.yml

  - name: Install Docker
    import_tasks: docker.yml

  roles:
  - gantsign.visual-studio-code
  - gantsign.golang
  - pixelart.chrome
  - chaosmail.sublime-text
  - gantsign.postman
  - m3nu.ansible_role_borgbackup
  - andrewrothstein.kubectl
  - andrewrothstein.terraform

  # - geerlingguy.pip not yet 20.04
  # - geerlingguy.docker not yet 20.04


  # - { role: dotfiles }

  # - role: stephdewit.nvm
  #   nvm_version: HEAD
