# from galaxy
- name: geerlingguy.dotfiles
- name: geerlingguy.docker
# - name: gantsign.visual-studio-code # not for 20.04
# - name: gantsign.golang # not for 20.04
- name: pixelart.chrome
# - name: chaosmail.sublime-text # not for 20.04
# - name: gantsign.postman # not for 20.04
# - name: m3nu.ansible_role_borgbackup # by borgbase :)
# - name: andrewrothstein.kubectl # not for 20.04 ??
# - name: andrewrothstein.terraform # not for 20.04 ??