# from galaxy
- name: geerlingguy.pip
- name: geerlingguy.docker
- name: geerlingguy.nodejs
- name: gantsign.visual-studio-code
- name: gantsign.golang
- name: pixelart.chrome
- name: chaosmail.sublime-text
- name: gantsign.postman
- name: m3nu.ansible_role_borgbackup
- name: andrewrothstein.kubectl
- name: andrewrothstein.terraform
- src: https://github.com/Joostvanderlaan/ansible-role-joplin.git
  scm: git
  name: joplin