# from galaxy
- name: gantsign.visual-studio-code
- name: gantsign.golang
- name: geerlingguy.pip
- name: geerlingguy.docker
- name: pixelart.chrome
- name: chaosmail.sublime-text
- name: gantsign.postman
- name: m3nu.ansible_role_borgbackup
- name: andrewrothstein.kubectl
- name: andrewrothstein.terraform